# Generated by Django 5.1 on 2024-10-02 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter a first name to be used for your wallet', max_length=20)),
                ('last_name', models.CharField(help_text='Enter a last name to be used for your wallet', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter your savings balance', max_digits=12)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(help_text='Enter the details of this transaction', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('savings_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.savings')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
